project:
  type: website

format:
  html:
    theme: cosmo
    css: .github/pages/styles.css
    toc: true
    keep-md: true
  commonmark: default

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating

metadata-files: [.github/pages/nbdev.yml, .github/pages/sidebar.yml]