project:
  type: website

format:
  html:
    theme: cosmo
    css: docs/styles.css
    toc: true
    keep-md: true
  commonmark: default

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating

metadata-files: [docs/nbdev.yml, docs/sidebar.yml]