# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/TradingAgent',
                'doc_host': 'https://MAT-Trading.github.io',
                'git_url': 'https://github.com/MAT-Trading/TradingAgent',
                'lib_path': 'src'},
  'syms': { 'src.fundemental': { 'src.fundemental.bar': ('tools/fundemental.html#bar', 'src/fundemental.py'),
                                 'src.fundemental.foo': ('tools/fundemental.html#foo', 'src/fundemental.py')}}}
