# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/TradingAgent',
                'doc_host': 'https://MAT-Trading.github.io',
                'git_url': 'https://github.com/MAT-Trading/TradingAgent',
                'lib_path': 'src'},
  'syms': { 'src.fundemental': { 'src.fundemental.get_financial_metrics': ( 'tools/fundemental.html#get_financial_metrics',
                                                                            'src/fundemental.py')}}}
