# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/tools/fundemental.ipynb.

# %% auto 0
__all__ = ['get_financial_metrics']

# %% ../notebooks/tools/fundemental.ipynb 3
from typing import Union, Dict
import yfinance as yf
from langchain_core.tools import tool


@tool
def get_financial_metrics(ticker: str) -> Union[Dict, str]:
    """Fetches key financial ratios for a given ticker."""
    try:
        stock = yf.Ticker(ticker)
        info = stock.info
        return {
            'pe_ratio': info.get('forwardPE'),
            'price_to_book': info.get('priceToBook'),
            'debt_to_equity': info.get('debtToEquity'),
            'profit_margins': info.get('profitMargins')
        }
    except Exception as e:
        return f"Error fetching ratios: {str(e)}"
